language: objective-c
before_install:
- chmod a+x ./Assets/.scripts/install.sh
- chmod a+x ./Assets/.scripts/build.sh
install:
- "./Assets/.scripts/install.sh"
script:
- "./Assets/.scripts/build.sh"
notifications:
  slack:
    rooms:
      secure: Lb2U1DJ6Y94+YPt3/zWHde0SEgtA1fYnv+zUQdZfp5mrUfjzwTXkDx9djj2UDQrFEOI8XaYrzVw9NzuvsomtXQ0TsROr09SJcbrahYRegSlQ8YwVfQuZZouvrBr5pi4JNleOyEr/xganmCm/ypsEilD4/I5iqco1TpfjZ0p6j2vugwPxAM4n3iuU2R5WntRMEXNv2nTcbZ31bG6NHh3W5rq903gfPUEkzKwe2q74rLMUz6GRnxXWQqjuyyu8Bot6LSZgSu6JXZDHd3qwWrU5uj65QlkZsDvK3JdAoQ+RtHViuVTRlltZ5naEAOddiieQ9EL32jLRA7O2OQELiXdrxnwMo5fOIE/37ny9QQHxLEtkmyC6UXbuv0AdYJeBkfvvNrhaO3/oRn8NNdO23QFp3fjTCYJWWBexZzuXHtFope5ntpsIVd5A2EO2tGwrgAyQoifpWmlHWImkUpZ/552vAb2L4UmaBG/RQDln5pKirh24SqJZkkCmODZUAg2GdKgk5L178SDhfYU1zx/45oZ48tVU7dUkHFK/1xfwVHvHXTRx9x71HOYLfJAGnqoOLqDIsxgu2Skm6FEXA1wWlbV1Ht8rDxLmp5Ej3kkPDRqg/O6M33axbVgE2Tjl9UEMiScrZISGJrSS7JDt3LrBc99DY0FVbzKtie++pXhTrKJ1ky8=
    on_success: change
    on_failure: change
