language: objective-c
before_install:
- chmod a+x ./Assets/.scripts/install.sh
- chmod a+x ./Assets/.scripts/build.sh
install:
- "./Assets/.scripts/install.sh"
script:
- "./Assets/.scripts/build.sh"
notifications:
  slack:
    secure: QLqfhvR6bJlM9fNxCFxd6YyPgMvbMuGGfZalbDEFaITov9kUdyLfo31tFDhXv/B22YK2kw6lY/fphwYECv0Kh4+uBmTCx2wGMNGOWSGi2axT/eqNS5U/MbJJl6Dr7fKkgCfVPgzGoQPARTGCnmTOeoHIvIhT9FvwNzIppk7ibOIw13nty+Nzj+6O6SwH3TQw3zZE/T5psdktw+yNDFuVEn2JB1uQ/7PMNUaT1ZKoM3UjnMNCiSOjYkDoR4UH/Hh2qi3xRoxo2uQH1O8/Gvq/n7xIaB276Yenh8STksZoTiC8mUNVQ6VKv9MJUrtSKxSo5SQYZO7/SC38fw0fnjJItMBGYAl7M+9HpNGPgLz9WOvsVyealBaRMTLUePEH9gn/xFnPf6p0jTBkhaOTUnh4RNu9Zz3CJyR0jQ1GsQ/evk1dwD5RJgjv8GyFHHzmqvLvHHfv0sqr9RC9JFIDwbhFl5yCgIMkkHiE+VQxELpIQDkASILoNbkebu1r8Akf1GUzLTUS/EW+CJy0nA5qmqG02r3EFIOVeni59qDCFgomj8OQLWjYYtT+L+6m03JEiLSJWLV6wINsQsg+Jz3iZupP4iCLWUTHJnecWt6gmm10PxmbzL4vsK6/of6DMGjZIZ+vUWC8yyUTgGQYvXsaZULa6U5wKCYz0AiPVFpDj4vsuLY=
